---

- name: "Install packages on {{ lsb_id }}"
  include_tasks: "{{ lsb_id }}.yml"

- name: "Add local system group {{ aehostd_group }}"
  group:
    name: "{{ aehostd_group }}"
    gid: "{{ aehostd_gid }}"
    state: present
    system: yes
  notify:
  - "restart aehostd"

- name: "Add local system account {{ aehostd_user }}"
  user:
    name: "{{ aehostd_user }}"
    comment: "aehostd system user"
    uid: "{{ aehostd_uid }}"
    group: "{{ aehostd_group }}"
    shell: "/bin/nologin"
    state: present
    system: yes
    createhome: no
    non_unique: no
  notify:
  - "restart aehostd"

- name: "CA certificate file {{ ldap_cacert_pathname }}"
  copy:
    src: "{{ ldap_cacert_filename }}"
    dest: "{{ ldap_cacert_pathname }}"
    owner: root
    group: root
    mode: 0644
  notify:
  - "restart aehostd"

- name: "Create {{ aehostd_conf_file }}"
  template:
    src: "{{ aehostd_conf_file|basename }}.j2"
    dest: "{{ aehostd_conf_file }}"
    owner: root
    group: "{{ aehostd_group }}"
    mode: 0640
  notify:
    - "restart aehostd"

- name: "Create /etc/sudoers.d/aehostd"
  template:
    src: "sudoers-aehostd.j2"
    dest: "/etc/sudoers.d/aehostd"
    owner: root
    group: root
    mode: 0440
  notify:
    - "refresh sudoers"

- name: "Create directory {{ aehostd_lib_dir }}"
  file:
    path: "{{ aehostd_lib_dir }}"
    state: directory
    owner: "{{ aehostd_user }}"
    group: "{{ aehostd_group }}"
    mode: 0751
  notify:
    - "restart aehostd"

- name: "Create directories for storing persistent files"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ aehostd_user }}"
    group: "{{ aehostd_group }}"
    mode: 0750
  with_items:
    - "{{ aehostd_db_dir }}"
    - "{{ aehostd_sshkeys_dir }}"
  notify:
    - "restart aehostd"

- name: "Create run-time directories of files"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ aehostd_user }}"
    group: "{{ aehostd_group }}"
    mode: 0755
  with_items:
    - "{{ aehostd_pid_file|dirname }}"
    - "{{ aehostd_socket|dirname }}"
  notify:
    - "restart aehostd"

- name: "Set host password in {{ aehostd_pw_file }}"
  copy:
    content: "{{ ldap_host_password }}"
    dest: "{{ aehostd_pw_file }}"
    owner: "{{ aehostd_user }}"
    group: "{{ aehostd_group }}"
    mode: 0640
  no_log: True
  when: ldap_host_password is defined and ldap_host_password != ""
  notify:
    - "restart aehostd"

- name: "Install systemd unit file"
  template:
    src: "aehostd.service.j2"
    dest: "/etc/systemd/system/aehostd.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - "restart aehostd"
  when: ansible_service_mgr == "systemd" and lsb_id != "SUSE"

- name: "Make sure systemd unit files are reloaded"
  systemd:
    daemon_reload: yes
  when: ansible_service_mgr == "systemd"

- name: "Ensure aehostd service is enabled and running"
  service:
    name: "aehostd"
    state: started
    enabled: yes
