---

- name: "Install packages on {{ lsb_id }}"
  include_tasks: "{{ lsb_id }}.yml"

- name: "Ensure nslcd service is disabled and stopped"
  service:
    name: "nslcd"
    state: stopped
    enabled: no
  notify:
    - "restart aehostd"

- name: "CA certificate file {{ ldap_cacert_pathname }}"
  copy:
    src: "{{ ldap_cacert_filename }}"
    dest: "{{ ldap_cacert_pathname }}"
    owner: root
    group: root
    mode: 0644
  notify:
  - "restart aehostd"

- name: "Create {{ aehostd_conf_file }}"
  template:
    src: "{{ aehostd_conf_file|basename }}.j2"
    dest: "{{ aehostd_conf_file }}"
    owner: root
    group: "{{ aehostd_gid }}"
    mode: 0640
  notify:
    - "restart aehostd"

- name: "Create directories for storing persistent files"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ aehostd_uid }}"
    group: "{{ aehostd_gid }}"
    mode: 0750
  with_items:
    - "{{ aehostd_pw_file|dirname }}"
    - "{{ aehostd_db_dir }}"
  notify:
    - "restart aehostd"

- name: "Create run-time directories of files"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ aehostd_uid }}"
    group: "{{ aehostd_gid }}"
    mode: 0755
  with_items:
    - "{{ aehostd_pid_file|dirname }}"
    - "{{ aehostd_socket|dirname }}"
  notify:
    - "restart aehostd"

- name: "Create {{ aehostd_pw_file }}"
  copy:
    content: "{{ ldap_host_password }}"
    dest: "{{ aehostd_pw_file }}"
    owner: "{{ aehostd_uid }}"
    group: "{{ aehostd_gid }}"
    mode: 0640
  when: ldap_host_password is defined and ldap_host_password != ""
  notify:
    - "restart aehostd"

- name: "Install systemd unit file"
  template:
    src: "aehostd.service.j2"
    dest: "/etc/systemd/system/aehostd.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - "restart aehostd"
  when: ansible_service_mgr == "systemd"

- name: "Make sure systemd unit files are reloaded"
  systemd:
    daemon_reload: yes
  when: ansible_service_mgr == "systemd"

- name: "Ensure aehostd service is running"
  service:
    name: "aehostd"
    state: started
    enabled: yes

- name: "Create sudo-ldap.conf"
  template:
    src: "sudo-ldap.conf.j2"
    dest: "{{ os_vars[lsb_id].sudo_ldap_conf }}"
    owner: root
    group: root
    mode: 0640
