---

- name: "Install aehostd"
  include_tasks: "{{ aehostd_lsb_id }}.yml"

- name: "Disable and stop other services"
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  ignore_errors: yes
  with_items: "{{ aehostd_stop_services }}"
  notify:
    - "restart aehostd services"

- name: "Add local system group {{ aehostd_group }}"
  group:
    name: "{{ aehostd_group }}"
    gid: "{{ aehostd_gid }}"
    state: present
    system: yes
  notify:
    - "restart aehostd"

- name: "Add local system account {{ aehostd_user }}"
  user:
    name: "{{ aehostd_user }}"
    comment: "aehostd system user"
    uid: "{{ aehostd_uid }}"
    group: "{{ aehostd_group }}"
    shell: "/bin/nologin"
    state: present
    system: yes
    createhome: no
    non_unique: no
  notify:
    - "restart aehostd"

- name: "CA certificate file {{ aehostd_cacert_pathname }}"
  copy:
    src: "{{ aehostd_cacert_filename }}"
    dest: "{{ aehostd_cacert_pathname }}"
    owner: root
    group: root
    mode: 0o0644
  when: aehostd_cacert_filename != ""
  notify:
    - "restart aehostd"

- name: "Create {{ aehostd_conf_file }}"
  template:
    src: "{{ aehostd_conf_file|basename }}.j2"
    dest: "{{ aehostd_conf_file }}"
    owner: root
    group: "{{ aehostd_group }}"
    mode: 0o0640
  notify:
    - "restart aehostd"

- name: "Create directory {{ aehostd_lib_dir }}"
  file:
    path: "{{ aehostd_lib_dir }}"
    state: directory
    owner: "{{ aehostd_user }}"
    group: "{{ aehostd_group }}"
    mode: 0o0751
  notify:
    - "restart aehostd"

- name: "Create directories for storing persistent files"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ aehostd_user }}"
    group: "{{ aehostd_group }}"
    mode: 0o0750
  with_items:
    - "{{ aehostd_db_dir }}"
    - "{{ aehostd_sshkeys_dir }}"
  notify:
    - "restart aehostd"

- name: "Create run-time directories of files"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ aehostd_user }}"
    group: "{{ aehostd_group }}"
    mode: 0o0755
  with_items:
    - "{{ aehostd_pid_file|dirname }}"
    - "{{ aehostd_socket|dirname }}"
  notify:
    - "restart aehostd"

- name: "Set host password in {{ aehostd_pw_file }}"
  copy:
    content: "{{ ldap_host_password }}"
    dest: "{{ aehostd_pw_file }}"
    owner: "{{ aehostd_user }}"
    group: "{{ aehostd_group }}"
    mode: 0o0640
  no_log: True
  when: ldap_host_password is defined and ldap_host_password != ""
  notify:
    - "restart aehostd"

- name: "Set ownership/permissions of {{ aehostd_pw_file }}"
  file:
    path: "{{ aehostd_pw_file }}"
    owner: "{{ aehostd_user }}"
    group: "{{ aehostd_group }}"
    mode: 0o0640
  ignore_errors: yes
  notify:
    - "restart aehostd"

- name: "Install systemd unit file for aehostd"
  template:
    src: "systemd/aehostd.service.j2"
    dest: "/etc/systemd/system/aehostd.service"
    owner: root
    group: root
    mode: 0o0644
  notify:
    - "restart aehostd"

- name: "Install tmpfiles config"
  copy:
    content: "d {{ aehostd_run_dir }} 0755 {{ aehostd_user }} {{ aehostd_group }}"
    dest: "/usr/lib/tmpfiles.d/aehostd.conf"
    owner: root
    group: root
    mode: 0o0644
  notify:
    - "restart aehostd services"

- name: "Install systemd unit file for aehostd-ph"
  template:
    src: "systemd/aehostd-ph.service.j2"
    dest: "/etc/systemd/system/aehostd-ph.service"
    owner: root
    group: root
    mode: 0o0644
  notify:
    - "restart aehostd-ph"
  when: ansible_service_mgr == "systemd"

- name: "Make sure systemd unit files are reloaded"
  systemd:
    daemon_reload: yes
  when: ansible_service_mgr == "systemd"

- name: "Ensure aehostd services are enabled and running"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - aehostd
    - aehostd-ph
