---

- name: "Install packages"
  yum:
    name:
      - sudo
    state: present
    update_cache: yes

- name: "Install NSS and PAM modules"
  yum:
    name:
      - aehostd-modules
    state: present
    update_cache: no

- block:

  - name: "Check whether all C wrapper modules are installed"
    command: "{{ aehostd_python }} -c 'import ldap0'"
    ignore_errors: yes
    register: ldap0_installed

  - name: "Install C compiler packages"
    yum:
      name:
        - gcc
        - openssl-devel
        - cyrus-sasl-devel
        - openldap-devel
        - python3-devel
        - libffi-devel
      state: present
      update_cache: no
    when: ldap0_installed.rc != 0

  when: aehostd_pip_needs_compiler==True

- name: "Install aehostd in virtual env"
  include_tasks: "venv.yml"

- name: "Uninstall C compiler packages"
  yum:
    name:
      - gcc
      - openssl-devel
      - cyrus-sasl-devel
      - openldap-devel
      - python3-devel
      - libffi-devel
    state: absent
    autoremove: yes
    update_cache: no
