---

- name: "Install base OS packages"
  apt:
    name:
      - libpam-aedir
      - libnss-aedir
      - sudo
      - python3-venv
    state: present
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
    dpkg_options: 'force-confold,force-confdef'

- name: "Install aehostd in {{ lsb_id }} in virtual env"
  include_tasks: "venv.yml"
