---

- name: "Add AE-DIR repository key"
  copy:
    src: "{{ item.value.key }}"
    dest: "/etc/apt/trusted.gpg.d/{{ item.value.key }}.asc"
    owner: root
    group: root
    mode: 0o0644
  with_dict: "{{ aehostd_pkg_repos }}"

- name: "Add AE-DIR Debian repository"
  apt_repository:
    filename: "{{ item.key }}"
    repo: "{{ item.value.repo }}"
    state: present
    update_cache: yes
  with_dict: "{{ aehostd_pkg_repos }}"

- name: "Install base OS packages"
  apt:
    name:
      - sudo
    state: present
    update_cache: yes
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'

- name: "Install NSS and PAM modules"
  apt:
    name: "{{ aehostd_module_packages }}"
    state: present
    update_cache: no
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'

- name: "Install aehostd and its dependencies"
  apt:
    name:
      - python3-aedir
      - python3-ldap0
      - aehostd
    state: present
    update_cache: no
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  notify:
    - "restart aehostd services"
