---

- name: "Install packages on {{ lsb_id }}"
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
    dpkg_options: 'force-confold,force-confdef'
  with_items:
    - libpam-aedir
    - libnss-aedir
    - sudo

- name: "Prepare virtualenv /opt/ae-dir needed for PIP installation"
  pip:
    name:
      - pip
      - setuptools
    state: latest
    virtualenv: "/opt/ae-dir"
    virtualenv_site_packages: no
    virtualenv_python: python2.7

- name: "Additional PIP packages in virtualenv /opt/ae-dir on {{ lsb_id }}"
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "/opt/ae-dir"
    virtualenv_python: python2.7
  with_items:
    - pyasn1
    - pyasn1_modules
    - ldap0
    - aedir
    - aehostd
  notify:
    - restart aehostd
