---
# tasks file for roles/ae-linux-login

# SSH authorized keys
#-----------------------------------------------------------------------

- name: "Create directory for pre-installed SSH authorized keys {{ sshd_authorized_keys }}"
  file:
    path: "{{ sshd_authorized_keys }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: "Install SSH emergency root key(s)"
  copy:
    src: "{{ ssh_emergency_root_keys }}"
    dest: "/etc/ssh/authorized_keys/root"
    owner: root
    group: root
    mode: 0640

- name: "Install SSH trusted user CA key(s)"
  copy:
    src: "{{ ssh_trusted_userca_keys|dirname }}"
    dest: "{{ ssh_trusted_userca_keys }}"
    owner: root
    group: root
    mode: 0640
  when:
    ssh_trusted_userca_keys != ""

# Install a NSS/PAM caching demon
#-----------------------------------------------------------------------

- name: "Install AE-DIR host demon for module {{ nsswitch_module }}"
  include_tasks: "aehostd.yml"

- name: "Install name service caching demon (nscd)"
  include_tasks: "nscd.yml"
  when:
    nscd_enabled == True

# sshd, NSS and PAM configuration
# these should be the last tasks!
#-----------------------------------------------------------------------

- name: "Install sshd_config based on {{ sshd_config_template }}"
  template:
    src: "{{ sshd_config_template }}"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: 0640
    validate: "/usr/sbin/sshd -t -f %s"
  notify: restart sshd

- name: "ensure SSH demon is running"
  service: name="{{ sshd_service_name }}" state=started enabled=yes

- name: "Create nsswitch.conf"
  template:
    src: "nsswitch.conf.j2"
    dest: "/etc/nsswitch.conf"
    owner: root
    group: root
    mode: 0644

- name: "Install PAM config files from {{ pam_template_dir }}/"
  template:
    src: "{{ item }}"
    dest: "/etc/pam.d/{{ (item|basename)[:-3] }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    "{{ pam_template_dir }}/*.j2"
  tags:
    - pam

- name: "Install sudoers file"
  template:
    src: "sudoers.j2"
    dest: "/etc/sudoers"
    owner: root
    group: root
    mode: 0440
