---

- name: "Disable and stop other NSS/PAM services"
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  ignore_errors: yes
  with_items:
    - sssd
    - nslcd
  notify:
  - "restart aehostd"

# SSH authorized keys
#-----------------------------------------------------------------------

- name: "Create directory for pre-installed SSH authorized keys {{ aehostd_sshd_authorized_keys }}"
  file:
    path: "{{ aehostd_sshd_authorized_keys }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: "Install SSH emergency root key(s)"
  copy:
    src: "{{ aehostd_sshd_emergency_root_keys }}"
    dest: "/etc/ssh/authorized_keys/root"
    owner: root
    group: root
    mode: 0640
  when:
    aehostd_sshd_emergency_root_keys != ""

- name: "Install SSH trusted user CA key(s)"
  copy:
    src: "{{ inventory_dir }}/files/{{ aehostd_sshd_trusted_userca_keys|basename }}"
    dest: "{{ aehostd_sshd_trusted_userca_keys }}"
    owner: root
    group: root
    mode: 0640
  when:
    aehostd_sshd_trusted_userca_keys != ""

- name: "Install AE-DIR host demon for module {{ aehostd_nss_module }}"
  include_tasks: "aehostd.yml"

# sshd, NSS and PAM configuration
# these should be the last tasks!
#-----------------------------------------------------------------------

- name: "Install sshd_config based on {{ aehostd_sshd_config_template }}"
  template:
    src: "{{ aehostd_sshd_config_template }}"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: 0640
    validate: "/usr/sbin/sshd -t -f %s"
  notify: restart sshd

- name: "ensure SSH demon is running"
  service:
    name: "{{ aehostd_sshd_service_name }}"
    state: started
    enabled: yes

- name: "Create nsswitch.conf"
  template:
    src: "nsswitch.conf.j2"
    dest: "/etc/nsswitch.conf"
    owner: root
    group: root
    mode: 0644

- name: "Install PAM config files from {{ aehostd_pam_template_dir }}/"
  template:
    src: "{{ item }}"
    dest: "/etc/pam.d/{{ (item|basename)[:-3] }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    "{{ aehostd_pam_template_dir }}/*.j2"
  tags:
    - pam

- name: "Install sudoers file"
  template:
    src: "sudoers.j2"
    dest: "/etc/sudoers"
    owner: root
    group: root
    mode: 0440
