---

- name: "Install packages on {{ lsb_id }}"
  zypper:
    name:
      - python3-ldap0>=0.6.8
      - python3-aedir>=0.7.0
      - python3-lockfile
      - python3-python-daemon
      - aehostd-modules
      - "aehostd >= 0.11.4"
      - sudo
    state: latest
    disable_recommends: yes
    type: package
  notify:
    - "restart aehostd"
