---

- name: "Install packages on {{ lsb_id }}"
  zypper:
    name: "{{ item }}"
    state: latest
    disable_recommends: yes
    type: package
  with_items:
    - nss-pam-ldapd
    - python-setuptools
    - python-ldap0
    - python-aedir
    - python-lockfile
    - python-python-daemon
    - aehostd
    - sudo
  notify:
    - "restart aehostd"
