---

- name: "Install packages on {{ lsb_id }}"
  zypper:
    name:
      - python-ldap0
      - python-aedir
      - python-lockfile
      - python-python-daemon
      - aehostd-modules
      - aehostd
      - sudo
    state: latest
    disable_recommends: yes
    type: package
  notify:
    - "restart aehostd"
