---

- name: "Install packages"
  zypper:
    name:
      - python3-ldap0>=0.6.10
      - python3-aedir>=0.8.5
      - python3-lockfile
      - python3-python-daemon
      - aehostd-modules
      - "aehostd >= 1.0.0"
      - sudo
    state: latest
    disable_recommends: yes
    type: package
  notify:
    - "restart aehostd"
