---

- name: "Install packages on {{ lsb_id }}"
  zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: yes
    type: package
  with_items:
    - nss-pam-ldapd
    - aehostd
    - sudo
