---

- name: "Prepare virtualenv /opt/ae-dir needed for PIP installation"
  pip:
    name:
      - pip
      - setuptools
    state: latest
    virtualenv: "/opt/ae-dir"
    virtualenv_site_packages: no
    virtualenv_command: "pyvenv"

- name: "Additional PIP packages in virtualenv /opt/ae-dir on {{ lsb_id }}"
  pip:
    name:
      - pyasn1
      - pyasn1_modules
      - ldap0>=0.6.4
      - aedir>=0.7.0
      - aehostd>=0.11.0
    state: latest
    virtualenv: "/opt/ae-dir"
  notify:
    - restart aehostd
