---

- name: "Prepare virtualenv /opt/ae-dir needed for PIP installation"
  pip:
    name:
      - pip
      - setuptools
    state: latest
    virtualenv: "/opt/ae-dir"
    virtualenv_site_packages: no
    virtualenv_command: "python3 -m venv"

- name: "Additional PIP packages in virtualenv /opt/ae-dir"
  pip:
    name:
      - pyasn1
      - pyasn1_modules
      - ldap0>=0.6.8
      - aedir>=0.8.5
      - aehostd>=1.0.0
    state: latest
    virtualenv: "/opt/ae-dir"
  notify:
    - restart aehostd
