---
# handlers file for roles/ae-dir-linux-client

- name: "restart ae-dir-hostd"
  service: name=ae-dir-hostd state=restarted

- name: "restart ssh"
  service: name="ssh" state=restarted

- name: "restart sshd"
  service: name="sshd" state=restarted
