---
# handlers file for roles/ae-dir-linux-client

- name: "restart aehostd"
  listen:
    - "restart aehostd"
    - "restart aehostd services"
  service:
    name: "aehostd"
    state: restarted

- name: "restart aehostd-ph"
  listen:
    - "restart aehostd-ph"
    - "restart aehostd services"
  service:
    name: "aehostd-ph"
    state: restarted
  when: ansible_service_mgr != "systemd"

- name: "restart ssh"
  listen:
    - "restart ssh"
  service:
    name: "ssh"
    state: restarted

- name: "restart sshd"
  listen:
    - "restart sshd"
  service:
    name: "sshd"
    state: restarted
