---
# handlers file for roles/ae-dir-linux-client

- name: "restart aehostd"
  service: name=aehostd state=restarted

- name: "restart ssh"
  service: name="ssh" state=restarted

- name: "restart sshd"
  service: name="sshd" state=restarted
